# Generated by Django 2.2.12 on 2020-05-07 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.TextField(max_length=50)),
                ('ticket_name', models.TextField(max_length=100)),
                ('assignment_name', models.TextField()),
                ('author', models.TextField()),
                ('createdon', models.DateTimeField(default=datetime.datetime(2020, 5, 7, 8, 40, 37, 340176))),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
