# Generated by Django 2.2.12 on 2020-05-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='createdon',
            field=models.DateTimeField(),
        ),
    ]
