# Generated by Django 2.2.12 on 2020-05-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignment_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='author',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_name',
            field=models.CharField(max_length=100),
        ),
    ]
