# Generated by Django 2.2.12 on 2020-05-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20200507_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
