# Generated by Django 2.2.12 on 2020-05-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='createdon',
            field=models.CharField(max_length=100),
        ),
    ]
