# Generated by Django 2.2.12 on 2020-05-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelNewServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.CharField(max_length=100)),
                ('loglocation', models.CharField(max_length=100)),
                ('createdby', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
