# Generated by Django 2.2.12 on 2020-05-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_modelnewserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelnewserver',
            name='createdon',
        ),
    ]
