# Generated by Django 2.2.12 on 2020-05-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertmgmt', '0002_auto_20200503_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterModel',
        ),
    ]
