# Generated by Django 2.2.12 on 2020-05-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertmgmt', '0003_delete_filtermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFilterFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_sort', models.CharField(max_length=128)),
                ('severity_fields', models.CharField(max_length=128)),
            ],
        ),
    ]
