# Generated by Django 2.2.12 on 2020-05-03 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alertmgmt', '0005_auto_20200503_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfilterfields',
            name='end_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logfilterfields',
            name='end_time',
            field=models.CharField(default='23:59:59', max_length=128),
        ),
        migrations.AddField(
            model_name='logfilterfields',
            name='start_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logfilterfields',
            name='start_time',
            field=models.CharField(default='00:00:00', max_length=128),
        ),
    ]
