# Generated by Django 2.2.12 on 2020-05-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertmgmt', '0006_auto_20200503_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfilterfields',
            name='page_no',
            field=models.IntegerField(default=1),
        ),
    ]
