# Generated by Django 2.2.12 on 2020-05-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertmgmt', '0007_logfilterfields_page_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfilterfields',
            name='log_src_url',
            field=models.CharField(default='all', max_length=100),
        ),
    ]
