# Generated by Django 2.2.12 on 2020-05-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertmgmt', '0008_logfilterfields_log_src_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=128)),
                ('assignee', models.CharField(max_length=100)),
                ('assignto', models.CharField(max_length=100)),
                ('ackstatus', models.IntegerField(default=0)),
            ],
        ),
    ]
