# Generated by Django 2.2.12 on 2020-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertmgmt', '0009_newassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassignment',
            name='ackstatus',
            field=models.BooleanField(default=False),
        ),
    ]
